services:
  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: deal
      POSTGRES_USER: deal_worker
      POSTGRES_PASSWORD: deal_worker
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/deal
      - --username=deal_worker
      - --password=deal_worker
      - update
    volumes:
      - ./src/main/resources/migrations:/liquibase/changelog
    networks:
      - backend
volumes:
  postgresql: { }

networks:
  backend: { }