spring:
  application:
    name: deal
  datasource:
    url: jdbc:postgresql://postgresql:5432/deal
    username: deal_worker
    password: deal_worker
  liquibase:
    enabled: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        format_sql: true
    database: postgresql
  kafka:
    bootstrap-servers: kafka:9091
    topic:
      finish-registration: finish-registration
      create-documents: create-documents
      send-documents: send-documents
      send-ses: send-ses
      credit-issued: credit-issued
      application-denied: application-denied

server:
  port: 8092

springdoc:
  swagger-ui:
    path: /swagger-ui

feign-client:
  conveyor-client:
    base-url: http://conveyor:8091
    offers-path: /conveyor/offers
    calculation-path: /conveyor/calculation
    retryer:
      period: 100
      max-period: 10000
      max-attempts: 2
